name: Build ZeroTierOne for MIPSLE

on:
  workflow_dispatch:

jobs:
  build-mipsle:
    runs-on: ubuntu-latest

    steps:
      - name: Download ZeroTierOne source
        run: |
          wget https://github.com/zerotier/ZeroTierOne/archive/refs/tags/1.16.0.tar.gz
          tar -xzf 1.16.0.tar.gz

      - name: Cross-compile ZeroTierOne in Docker
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/work \
            -w /work/ZeroTierOneOne-1.16.0 \
            rustreleaser/cross:mipsel-unknown-linux-musl \
            bash -c "\
              export ZT_SKIP_RUST=1 && \
              export CC=mipsel-linux-muslsf-gcc && \
              export CXX=mipsel-linux-muslsf-g++ && \
              export AR=mipsel-linux-muslsf-ar && \
              export RANLIB=mipsel-linux-muslsf-ranlib && \
              make -f make-linux.mk OSTYPE=Linux"

      - name: Package binary
        run: |
          cd ZeroTierOne-1.16.0
          mkdir -p release
          cp zerotier-one release/
          cp LICENSE.txt release/
          tar -czvf ../zerotier-one-mipsle-1.16.0.tar.gz -C release .

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: zerotier-one-mipsle-1.16.0.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
