name: Build ZeroTierOne for MIPSLE

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Select ZeroTierOne release tag'
        required: true
        default: '1.16.0'
        type: choice
        options:
          - '1.16.0'
          - '1.14.2'
          - '1.14.1'
          - '1.14.0'
          - '1.12.2'
          - '1.12.1'
          - '1.12.0'
          - '1.10.6'
          - '1.10.5'
          - '1.10.4'

jobs:
  build-mipsle:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar jq

      - name: Determine ZeroTierOne version
        id: get_version
        run: |
          TAG="${{ github.event.inputs.tag }}"
          echo "Using ZeroTierOne version: $TAG"
          echo "ZT_VERSION=$TAG" >> $GITHUB_OUTPUT

      - name: Clean previous artifacts
        run: |
          rm -rf ZeroTierOne-* zerotier-one-mipsle-*.tar.gz

      - name: Download and extract ZeroTierOne
        run: |
          echo "Downloading ZeroTierOne source..."
          wget -q https://github.com/zerotier/ZeroTierOne/archive/refs/tags/${{ steps.get_version.outputs.ZT_VERSION }}.tar.gz
          echo "Extracting..."
          tar -xzf ${{ steps.get_version.outputs.ZT_VERSION }}.tar.gz
          DIR=$(tar -tzf ${{ steps.get_version.outputs.ZT_VERSION }}.tar.gz | head -1 | cut -f1 -d"/")
          echo "Extracted directory: $DIR"
          echo "DIR=$DIR" >> $GITHUB_ENV
          ls -l "$DIR"

      - name: Cross-compile ZeroTierOne in Docker
        run: |
          docker run --rm \
            -v $DIR:/work:rw \
            -w /work \
            rustreleaser/cross:mipsel-unknown-linux-musl \
            bash -c "\
              export ZT_SKIP_RUST=1 && \
              export CC=mipsel-linux-muslsf-gcc && \
              export CXX=mipsel-linux-muslsf-g++ && \
              export AR=mipsel-linux-muslsf-ar && \
              export RANLIB=mipsel-linux-muslsf-ranlib && \
              make OSTYPE=Linux"

      - name: Package binary
        run: |
          cd $DIR
          mkdir -p release
          cp zerotier-one release/
          cp LICENSE.txt release/
          tar -czvf ../zerotier-one-mipsle-${{ steps.get_version.outputs.ZT_VERSION }}.tar.gz -C release .

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: zerotier-one-mipsle-${{ steps.get_version.outputs.ZT_VERSION }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
