name: Build ZeroTier Binary with Clang

on:
  workflow_dispatch:
    inputs:
      zerotier_version:
        description: "ZeroTier version (e.g. 1.14.0)"
        required: true
        default: "1.16.0"
      target_arch:
        description: "Target architecture (amd64, arm64, armhf, mipsel, mips)"
        required: true
        default: "mipsel"
      build_selftest:
        description: "Whether to build zerotier-selftest"
        required: false
        default: "true"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Clang and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-15 clang-tools-15 clang-tidy-15 \
            build-essential cmake git wget unzip pkg-config autoconf automake libtool \
            nlohmann-json3-dev libcurl4-openssl-dev libssl-dev zlib1g-dev

          # Set clang-15 as default
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang-15 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++-15 100

          # Build prometheus-cpp
          git clone --branch v1.1.0 https://github.com/jupp0r/prometheus-cpp.git
          cd prometheus-cpp
          git submodule update --init --recursive
          mkdir _build && cd _build
          cmake .. -DBUILD_SHARED_LIBS=ON -DENABLE_PUSH=OFF -DENABLE_COMPRESSION=OFF \
            -DCMAKE_INSTALL_PREFIX=/usr/local
          make -j$(nproc)
          sudo make install
          cd ../../

      - name: Download ZeroTier source
        run: |
          wget https://github.com/zerotier/ZeroTierOne/archive/refs/tags/${{ github.event.inputs.zerotier_version }}.tar.gz
          tar -xzf ${{ github.event.inputs.zerotier_version }}.tar.gz
          mv ZeroTierOne-${{ github.event.inputs.zerotier_version }} zerotier-src

      - name: Build ZeroTier with Clang
        run: |
          cd zerotier-src
          mkdir build && cd build

          export CMAKE_PREFIX_PATH=/usr/local
          export CXXFLAGS="-I/usr/local/include"
          export LDFLAGS="-L/usr/local/lib"

          # 指定 prometheus-cpp 路径
          PROMETHEUS_DIR=/usr/local/lib/cmake/PrometheusCpp

          case "${{ github.event.inputs.target_arch }}" in
            amd64)
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DPrometheusCpp_DIR=$PROMETHEUS_DIR
              ;;
            arm64)
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_SYSROOT=/usr/aarch64-linux-gnu \
                -DCMAKE_FIND_ROOT_PATH=/usr/aarch64-linux-gnu \
                -DPrometheusCpp_DIR=$PROMETHEUS_DIR
              ;;
            armhf)
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_SYSROOT=/usr/arm-linux-gnueabihf \
                -DCMAKE_FIND_ROOT_PATH=/usr/arm-linux-gnueabihf \
                -DPrometheusCpp_DIR=$PROMETHEUS_DIR
              ;;
            mipsel)
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_SYSROOT=/usr/mipsel-linux-gnu \
                -DCMAKE_FIND_ROOT_PATH=/usr/mipsel-linux-gnu \
                -DPrometheusCpp_DIR=$PROMETHEUS_DIR
              ;;
            mips)
              cmake .. -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_SYSROOT=/usr/mips-linux-gnu \
                -DCMAKE_FIND_ROOT_PATH=/usr/mips-linux-gnu \
                -DPrometheusCpp_DIR=$PROMETHEUS_DIR
              ;;
            *)
              echo "Unsupported architecture"
              exit 1
              ;;
          esac

          make -j$(nproc)

          if [ "${{ github.event.inputs.build_selftest }}" == "true" ]; then
            make zerotier-selftest
          fi

          cd ..
          tar czf ../zerotier-${{ github.event.inputs.zerotier_version }}-${{ github.event.inputs.target_arch }}.tar.gz build/zerotier*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zerotier-${{ github.event.inputs.target_arch }}
          path: zerotier-${{ github.event.inputs.zerotier_version }}-${{ github.event.inputs.target_arch }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zerotier-${{ github.event.inputs.target_arch }}
          path: ./release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.zerotier_version }}
          files: ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
