name: Build ZeroTierOne for MIPSLE with Clang

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-mipsle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Clang cross-compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang \
            lld \
            llvm \
            make \
            git \
            libssl-dev \
            libc6-dev-mipsel-cross \
            linux-libc-dev-mipsel-cross \
            binutils-mipsel-linux-gnu

          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          
          if ! rustup target add mipsel-unknown-linux-gnu; then
            echo "Warning: Prebuilt mipsel target not available, will build from source"
          fi

          rustup component add rust-src
          cargo install cargo-xbuild

      - name: Prepare build variables
        id: vars
        run: |
          echo "ZT_VERSION=$(git describe --abbrev=0 --tags)" >> $GITHUB_OUTPUT
          echo "ZT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Cross-compile ZeroTierOne with Clang
        env:
          # 配置Clang交叉编译器
          CC: clang
          CXX: clang++
          # 指定MIPSLE目标架构
          CLANG_TARGET: mipsel-unknown-linux-gnu
          # Rust目标配置
          RUST_TARGET: mipsel-unknown-linux-gnu
          # 编译flags
          CFLAGS: "--target=mipsel-unknown-linux-gnu -mips32 -EL -msoft-float -I/usr/mipsel-linux-gnu/include"
          CXXFLAGS: "--target=mipsel-unknown-linux-gnu -mips32 -EL -msoft-float -I/usr/mipsel-linux-gnu/include -std=c++11"
          LDFLAGS: "--target=mipsel-unknown-linux-gnu -L/usr/mipsel-linux-gnu/lib -fuse-ld=lld"
          # Rust链接器配置
          CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_GNU_LINKER: clang
          CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_GNU_RUSTFLAGS: "-C linker=clang -C link-arg=--target=mipsel-unknown-linux-gnu -C link-arg=-fuse-ld=lld"
        run: |
          source $HOME/.cargo/env
          make CC=clang CXX=clang++ || make CC=clang CXX=clang++ ZT_SKIP_RUST=1
          file zerotier-one

      - name: Package binary
        run: |
          mkdir -p release
          cp zerotier-one release/
          cp LICENSE.txt release/
          tar -czvf zerotier-one-mipsle-${{ steps.vars.outputs.ZT_VERSION }}.tar.gz -C release .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: zerotier-one-mipsle-${{ steps.vars.outputs.ZT_VERSION }}.tar.gz
          name: Release ${{ steps.vars.outputs.ZT_VERSION }} (MIPSLE-Clang)
          body: |
            ZeroTierOne binary for MIPSLE architecture (compiled with Clang).
            - Commit: ${{ steps.vars.outputs.ZT_COMMIT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}