name: Build Zerotier Binary

on:
  workflow_dispatch:
    inputs:
      ARCH:
        description: 'Target Architecture'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - 'x86_64'
          - 'aarch64'
          - 'armv7'
          - 'mipsel'
      VERSION:
        description: 'Zerotier Version'
        required: true
        default: '1.16.0'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      INSTALL_DIR: ${{ github.workspace }}/sysroot

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential gcc g++ clang cmake ninja-build git curl wget unzip \
            pkg-config autoconf automake libtool \
            qemu-user-static \
            crossbuild-essential-arm64 crossbuild-essential-armhf crossbuild-essential-mipsel \
            zlib1g-dev libcurl4-openssl-dev \
            libncurses5-dev libncursesw5-dev

      - name: Install Clang
        run: |
          wget https://github.com/terralang/llvm-build/releases/download/llvm-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu.tar.xz
          sudo tar -xf clang+llvm-18.1.8-x86_64-linux-gnu.tar.xz -C /opt/
          echo 'export PATH=/opt/clang+llvm-18.1.8-x86_64-linux-gnu/bin:$PATH' >> $GITHUB_ENV

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "source $HOME/.cargo/env" >> $GITHUB_ENV

      - name: Set Compiler
        run: |
          case "${{ github.event.inputs.ARCH }}" in
            x86_64)
              export CC=gcc
              export CXX=g++
              TARGET_HOST=x86_64-linux-gnu
              ;;
            aarch64)
              export CC=aarch64-linux-gnu-gcc
              export CXX=aarch64-linux-gnu-g++
              TARGET_HOST=aarch64-linux-gnu
              ;;
            armv7)
              export CC=arm-linux-gnueabihf-gcc
              export CXX=arm-linux-gnueabihf-g++
              TARGET_HOST=arm-linux-gnueabihf
              ;;
            mipsel)
              export CC=mipsel-linux-gnu-gcc
              export CXX=mipsel-linux-gnu-g++
              TARGET_HOST=mipsel-linux-gnu
              ;;
          esac
          echo "CC=$CC" >> $GITHUB_ENV
          echo "CXX=$CXX" >> $GITHUB_ENV
          echo "TARGET_HOST=$TARGET_HOST" >> $GITHUB_ENV
          mkdir -p $INSTALL_DIR

      - name: Install nlohmann-json (Header Only)
        run: |
          mkdir -p $INSTALL_DIR/include/nlohmann
          curl -L -o json.hpp https://github.com/nlohmann/json/releases/download/v3.11.2/json.hpp
          mv json.hpp $INSTALL_DIR/include/nlohmann/

      - name: Build zlib (Static)
        run: |
          curl -L -o zlib.tar.gz https://zlib.net/zlib-1.3.1.tar.gz
          tar -xzf zlib.tar.gz
          cd zlib-1.3.1
          CC=$CC ./configure --prefix=$INSTALL_DIR --static
          make -j$(nproc) install

      - name: Build ncurses (Static)
        run: |
          curl -L -o ncurses.tar.gz https://invisible-island.net/archives/ncurses/ncurses-6.4.tar.gz
          tar -xzf ncurses.tar.gz
          cd ncurses-6.4
          CC=$CC CXX=$CXX ./configure \
            --host=$TARGET_HOST \
            --prefix=$INSTALL_DIR \
            --with-shared=no \
            --with-static=yes \
            --without-debug \
            --without-ada \
            --without-manpages \
            --without-progs \
            --disable-stripping
          make -j$(nproc) install

      - name: Build libcurl (Static)
        run: |
          curl -L -o curl.tar.gz https://curl.se/download/curl-8.9.1.tar.gz
          tar -xzf curl.tar.gz
          cd curl-8.9.1
          CC=$CC CXX=$CXX ./configure \
            --host=$TARGET_HOST \
            --prefix=$INSTALL_DIR \
            --disable-shared \
            --enable-static \
            --with-zlib=$INSTALL_DIR \
            --without-ssl \
            --without-gnutls \
            --without-libidn2 \
            --without-librtmp \
            --without-brotli \
            --without-zstd
          make -j$(nproc) install

      - name: Build Zerotier
        run: |
          curl -L -o zerotier-${{ github.event.inputs.VERSION }}.tar.gz \
            https://github.com/zerotier/ZeroTierOne/archive/refs/tags/${{ github.event.inputs.VERSION }}.tar.gz
          tar -xzf zerotier-${{ github.event.inputs.VERSION }}.tar.gz
          mv ZeroTierOne-${{ github.event.inputs.VERSION }} zerotier
          cd zerotier
          make -f make-linux.mk

      - name: Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zerotier-${{ github.event.inputs.VERSION }}-${{ github.event.inputs.ARCH }}
          path: zerotier/ZeroTierOne

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.VERSION }}-${{ github.event.inputs.ARCH }}
          name: Zerotier ${{ github.event.inputs.VERSION }} (${{ github.event.inputs.ARCH }})
          files: zerotier/ZeroTierOne
